### ISSUE TITLE
负载均衡和反向代理同时配置

### ISSUE THREAD

**Issue by donyzhai** [hanshuaikang/HanShu-Note#2]
Hi，教程种反向代理时8080和8090端口分别对应了Hi和Hello两个页面，但是负载均衡的时候location配置是proxy_pass http://myserver;这还能实现访问不同的页面吗?

**Comment by hanshuaikang** [comment]
抱歉，我现在才看到。这个负载均衡本身就是可以和反向代理一起配置的，看你的描述应该是可以的，
